### ISSUE TITLE
Serialzation Exception when passing parameter from MVC Controller Action

### ISSUE THREAD

**Issue by gorillapower** [esskar/Serialize.Linq#113]
Im getting an exception on `expressionSerializer.SerializeText()` when trying to serialize an `Expression`, seemingly when it contains a reference from an MVC action controller. When assign a new local variable in its place with the same value, the serialization succeeds.

**Exception Detail**
```Error converting type: Type 'WhiteBox.WebApp.Helpers.ConnectorInstanceHelper+<>c__DisplayClass4_0' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a parameterless constructor - all public members of the type will then be serialized, and no attributes will be required.```

If I inspect the `Expression` while debugging, i can see the following difference between the local variable 

`.Constant<Whitebox.WebApp.Helpers.ConnectorInstanceHelper+<>c__DisplayClass4_0>(Whitebox.WebApp.Helpers.ConnectorInstanceHelper+<>c__DisplayClass4_0).productId`

and the one being passed from the controller action. The difference being the **CS$<>8__locals1** suffix.

`.Constant<Whitebox.WebApp.Helpers.ConnectorInstanceHelper+<>c__DisplayClass4_1>(Whitebox.WebApp.Helpers.ConnectorInstanceHelper+<>c__DisplayClass4_1).CS$<>8__locals1).productId`

-Visual Studio 2017
-Net CORE 2.2
-Microsoft.AspNetCore.MVC 2.2.0

**Comment by esskar** [comment]
Hey. Thanks for opening an issue. Can you post some code, so i am able to investigate more. Thanks.

**Comment by gorillapower** [comment]
Hi @esskar, sorry for delayed response. I tried to create a test case where i can consistently reproduce the issue. It still seems to be related to the naming I see in the debug view of the expression, but ive narrowed it down it bit further.

If you initiate the code with `await new TestClass().TestMethod("1231231");` the code within try-catch will throw an exception. The code after that executes without exception. If you move the `var userId = "12313";' outside the try-catch and similarily, if you remove the try-catch altogether (demonstrated by the subsequent code) the code executes fine. Its cases when the **CS$<>8__locals1** is present in the expression that the serialization seems to fail.

I also noted that removing the the `productId` parameter from `TestMethod` results in no errors.

```
public class TestClass
    {
        public TestClass() { }

        public async Task TestMethod(string productId)
        {
            try
            {
                var userId = "12313";
                DoSerialization<ProductTest>(x => x.UserId == userId && x.ProductId == productId);
            }
            catch (Exception)
            {
                Trace.WriteLine("Exception thrown");
            }

            var userId2 = "12313";
            DoSerialization<ProductTest>(x => x.UserId == userId2 && x.ProductId == productId);
        }

        public static void DoSerialization<T>(Expression<Func<T, bool>> predicate)
        {
            var expressionSerializer = new ExpressionSerializer(new Serialize.Linq.Serializers.JsonSerializer());
            var queryJson = expressionSerializer.SerializeText(predicate);
        }
    }
    public class ProductTest
    {
        public string ProductId { get; set; }

        public string UserId { get; set; }
    }

    public class UserTest
    {
        public string Email { get; set; }
        public string UserId { get; set; }
    }

```

**Comment by esskar** [comment]
@gorillapower i fixed it; will push new version by tomorrow

**Comment by esskar** [comment]
I just pushed version 1.8.0 via nuget. Can you please test?

**Comment by gorillapower** [comment]
@esskar, thanks so much or the response and update. It seems that im still getting an exception running the test code above.


![image](https://user-images.githubusercontent.com/8879065/56716495-d4f37580-673a-11e9-9ff5-1f3f439a58ef.png)


```at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Serialize.Linq.Factories.TypeResolverNodeFactory.TryGetConstantValueFromMemberExpression(MemberExpression memberExpression, Object& constantValue, Type& constantValueType)
   at Serialize.Linq.Factories.TypeResolverNodeFactory.TryGetConstantValueFromMemberExpression(MemberExpression memberExpression, Object& constantValue, Type& constantValueType)
   at Serialize.Linq.Factories.TypeResolverNodeFactory.ResolveMemberExpression(MemberExpression memberExpression)
   at Serialize.Linq.Nodes.BinaryExpressionNode.Initialize(BinaryExpression expression)
   at Serialize.Linq.Factories.NodeFactory.Create(Expression expression)
   at Serialize.Linq.Nodes.BinaryExpressionNode.Initialize(BinaryExpression expression)
   at Serialize.Linq.Factories.NodeFactory.Create(Expression expression)
   at Serialize.Linq.Nodes.LambdaExpressionNode.Initialize(LambdaExpression expression)
   at Serialize.Linq.Factories.NodeFactory.Create(Expression expression)
   at Serialize.Linq.Serializers.ExpressionSerializer.SerializeText(Expression expression, FactorySettings factorySettings)
   at MartinConsole.TestClass.DoSerialization[T](Expression`1 predicate) in C:\dev\Program.cs:line 42
   at MartinConsole.TestClass.TestMethod(String productId) in C:\dev\Program.cs:line 28```

**Comment by esskar** [comment]
Is there something else, because if i run this in a console app, it runs without problems

![image](https://user-images.githubusercontent.com/65206/56735738-95428300-6766-11e9-841b-0a7e10b11ef9.png)

**Comment by gorillapower** [comment]
Hi Sascha,

For me the exception is caught and writes "Exception Thrown". Does the code
not enter the Catch()?

**Comment by esskar** [comment]
I just pushed version 1.8.1 to nuget

**Comment by gorillapower** [comment]
Working! thanks so much
